import {
    AngelIcon,
    AssasinIcon,
    CircusIcon,
    DevilIcon,
    GhostIcon,
    KnightIcon,
    ManIcon,
    PrincessIcon,
    QueenIcon,
    SantaIcon,
    AlienIcon,
    FairyIcon,
    DefaultIcon,
  } from '../../../../assets/profileIcon';

export const icons = [
    {
        id:1,
        name:"AngelIcon",
        icon:()=>(<AssasinIcon/>),
    },
    {
        id:2,
        name:"AssasinIcon",
        icon:()=>(<AngelIcon/>),
    },
    {
        id:3,
        name:"CircusIcon",
        icon:()=>(<CircusIcon/>),
    },
    {
        id:4,
        name:"DevilIcon",
        icon:()=>(<DevilIcon/>),
    },
    {
        id:5,
        name:"GhostIcon",
        icon:()=>(<GhostIcon/>),
    },
    {
        id:6,
        name:"KnightIcon",
        icon:()=>(<KnightIcon/>),
    },
    {
        id:7,
        name:"ManIcon",
        icon:()=>(<ManIcon/>),
    },
    {
        id:8,
        name:"PrincessIcon",
        icon:()=>(<PrincessIcon/>)
    },
    {
        id:9,
        name:"QueenIcon",
        icon:()=>(<QueenIcon/>),
    },
    {
        id:10,
        name:"SantaIcon",
        icon:()=>(<SantaIcon/>),
    },
    {
        id:11,
        name:"AlienIcon",
        icon:()=>(<AlienIcon/>),
    },
    {
        id:12,
        name:"FairyIcon",
        icon:()=>(<FairyIcon/>),
    },
    {
        id:13,
        name:"DefaultIcon",
        icon:()=>(<DefaultIcon/>),
    },

    
]
